# Generated by Django 3.2 on 2022-11-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(null=True, verbose_name='سعر الكشف'),
        ),
    ]
